/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{svelte,js,ts}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#4cd6ff",
        "primary-fixed": "#b7eaff",
        "surface-container-high": "#2a2a2b",
        "on-secondary": "#003919",
        "surface-bright": "#3a393a",
        "tertiary-container": "#ad79e1",
        "surface-container-lowest": "#0e0e0f",
        error: "#ffb4ab",
        tertiary: "#ddb8ff",
        "on-error": "#690005",
        "surface-dim": "#131314",
        "surface-container-low": "#1c1b1c",
        surface: "#131314",
        "surface-container-highest": "#353436",
        "primary-container": "#009dc1",
        "secondary-container": "#25a55a",
        "inverse-on-surface": "#313031",
        "on-background": "#e5e2e3",
        "error-container": "#93000a",
        "inverse-surface": "#e5e2e3",
        "on-tertiary": "#470e78",
        "on-primary": "#003543",
        "primary-fixed-dim": "#4cd6ff",
        "outline-variant": "#414754",
        "on-error-container": "#ffdad6",
        "surface-variant": "#353436",
        primary: "#4cd6ff",
        "on-surface-variant": "#c1c6d7",
        "inverse-primary": "#00677f",
        outline: "#8b90a0",
        "tertiary-fixed-dim": "#ddb8ff",
        secondary: "#66dd8b",
        background: "#131314",
        "on-surface": "#e5e2e3",
        "surface-container": "#201f20",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        "2xl": "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
      },
    },
  },
  plugins: [],
};

